//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peridot.Veldrid 
{
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Peridot.Veldrid.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a #version 450
        ///
        ///layout(location = 0) in vec4 fsin_Color;
        ///layout(location = 1) in vec2 tex_coord;
        ///layout(location = 0) out vec4 fsout_Color;
        ///
        ///layout(set = 1, binding = 0) uniform texture2D Tex;
        ///layout(set = 1, binding = 1) uniform sampler Sampler;
        ///
        ///void main()
        ///{
        ///    //vTexture.Texture
        ///    fsout_Color = texture(sampler2D(Tex, Sampler), tex_coord);
        ///}.
        /// </summary>
        internal static string shader_frag {
            get {
                return ResourceManager.GetString("shader_frag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a #version 450
        ///layout (constant_id = 0) const bool InvertY = false;
        ///
        ///layout(location = 0) in vec2 Position;
        ///layout(location = 0) out vec4 fsin_Color;
        ///layout(location = 1) out vec2 tex_coord;
        ///
        ///struct Item 
        ///{
        ///    mat4 source;
        ///    vec4 color;
        ///    mat4 model;
        ///    mat4 projection;
        ///};
        ///
        ///layout(std430, binding = 0) readonly buffer Items
        ///{
        ///    mat4 view;
        ///    Item items[];
        ///};
        ///
        ///void main()
        ///{
        ///    Item item = items[gl_InstanceIndex];
        ///
        ///    vec2 uvBase = (Position + vec2(1)) * 0.5;
        ///    tex_coord =  [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string shader_vert {
            get {
                return ResourceManager.GetString("shader_vert", resourceCulture);
            }
        }
    }
}
